str = input("enter your string: ")

print(str.title())
print(str.upper())
print(str.capitalize())
print(str.casefold())
print(str.isalnum())
print(str.isalpha())
print(str.isascii())
print(str.isdecimal())
print(str.islower())
print(str.lower())
